src/rttr/detail/misc/standard_types.cpp
The linker error occurs due to the attributes ` __attribute__ ((__visibility__("hidden"), __always_inline__))` specified for the `std::string` methods in question.
It can be fixed by explicitly instantiating the `std::string` template as described [here](https://stackoverflow.com/questions/29324619/taking-pointer-to-member-stdstringsize-fails-to-link-with-libc-but-works-w).
=> Fix #3 by explicitly instantiating std::string template

src/rttr/detail/impl/enum_flags_impl.h, src/rttr/enum_flags.h
I replaced some occurrences of the RTTR_NO_CXX14_CONSTEXPR macro which I believe is used mistakenly in these places.
=> Replaced wrong RTTR_CXX14_CONSTEXPR macros

src/rttr/type.h
[Currently](http://www.rttr.org/doc/master/classrttr_1_1type.html#a697d434492a9fcc6bc108371b48b8033) no hyperlink.
=> Fix references to wrapper_mapper in documentation

src/rttr/detail/variant/variant_data_policy.h
variant_data_policy.h:598:17: warning: enumeration value 'EXTRACT_WRAPPED_VALUE' not handled in switch [-Wswitch]
=> Fix -Wswitch warning

src/rttr/detail/misc/standard_types.cpp, src/rttr/detail/type/type_data.h, src/rttr/detail/type/type_register.cpp, src/rttr/detail/type/type_register_p.h
will also appear when he use used as template parameter
in a template instance.
e.g:
```
std::reference_wrapper<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >
std::reference_wrapper<class std::string>
```
fixes #40
=> Feature use custom name in templates

src/rttr/detail/comparison/compare_array_equal_impl.h, src/rttr/detail/comparison/compare_equal.cpp, src/rttr/detail/comparison/compare_equal.h, src/rttr/detail/comparison/compare_equal_impl.h, src/rttr/detail/type/type_impl.h, src/rttr/detail/variant/variant_compare.cpp, src/rttr/detail/variant/variant_compare.h, src/rttr/detail/variant/variant_data_policy.h, src/rttr/detail/variant/variant_impl.h, src/rttr/variant.cpp, src/rttr/variant.h, src/unit_tests/unit_tests.cmake, src/unit_tests/variant/variant_cmp_equal_test.cpp, src/unit_tests/variant/variant_cmp_greater_or_equal.cpp, src/unit_tests/variant/variant_cmp_greater_test.cpp, src/unit_tests/variant/variant_cmp_less_or_equal.cpp
Added operators `>`, `<=`, `>=` for variant class.
The result of the `>` operator is implicit derived from a valid registered `<` and `==` operator.
fixes #61
=> Add new variant comparators

.travis.yml, src/rttr/detail/type/type_register.cpp, src/unit_tests/method/method_misc_test.cpp, src/unit_tests/property/property_class_inheritance.cpp
When the derived type has not class items(properties or methods),
then no class items were returned, altough the base class had properties.
This is now fixed.
fixes #87
=> Bugfix class items inheritance

3rd_party/rapidjson-1.1.0/rapidjson/document.h, CMake/config.cmake, CMake/utility.cmake
added cmake check for C++17 bug in MSVC compiler:
https://developercommunity.visualstudio.com/content/problem/192396/more-than-one-partial-specialization-compile-error.html
C++17 automatically disabled when using MSVC for the moment,
with a new update it will be enabled automatically
#118
=> fixed rapid json compile error because of warning

src/rttr/detail/variant_associative_view/variant_associative_view_creator.h, src/rttr/detail/variant_associative_view/variant_associative_view_creator_impl.h, src/rttr/detail/variant_sequential_view/variant_sequential_view_creator.h, src/rttr/detail/variant_sequential_view/variant_sequential_view_creator_impl.h, src/unit_tests/variant_sequential_view/variant_sequential_view_test.cpp
Only pointer types were correctly recognized. Because of using std::decay<T>.
Now the "is_sequential_container()" & "create_sequential_view()" function are using the same type.
Fixed this also for variant_associative_view. No test provided because, raw arrays are not associative container.
Added some more tests
=> fixed not honored raw arrays in variant_sequential_view

src/examples/json_serialization/from_json.cpp, src/rttr/constructor.cpp, src/rttr/constructor.h, src/rttr/detail/constructor/constructor_wrapper.h, src/rttr/detail/constructor/constructor_wrapper_base.cpp, src/rttr/detail/constructor/constructor_wrapper_base.h, src/rttr/detail/constructor/constructor_wrapper_defaults.h, src/unit_tests/constructor/constructor_misc_test.cpp
get_instanciated_type()" => "get_instantiated_type()"
REMARK: Minor API change because of type in "constructor" class!
fixes #83
=> fixed typo int "constructor" class

CMakeLists.txt, src/rttr/detail/misc/std_type_traits.h, src/rttr/detail/variant/variant_data_policy.h, src/rttr/detail/variant/variant_impl.h, src/rttr/variant.h, src/unit_tests/unit_tests.cmake, src/unit_tests/variant/variant_cast_test.cpp, src/unit_tests/variant/variant_misc_test.cpp
Added global "variant_cast" method
Added 4 overloads of the method "variant_cast"
In order to move values out, to return values by reference
or to return a pointer to the underlying values, when the type does match:
template<class T>
T variant_cast(variant&& operand);
template<class T>
T variant_cast(variant& operand);
template<class T>
T variant_cast(const variant& operand);
template<class T>
const T* variant_cast(const variant* operand) RTTR_NOEXCEPT;
template<class T>
T* variant_cast(variant* operand) RTTR_NOEXCEPT;
Additionally:
- added non-const version of variant::get_value()
- fixed copy-right year in root CMakeLists.txt file
Fixes #108
=> Feature add variant_cast

src/rttr/detail/impl/rttr_cast_impl.h, src/rttr/detail/impl/wrapper_mapper_impl.h, src/rttr/detail/misc/register_wrapper_mapper_conversion.h, src/rttr/detail/misc/utility.h, src/rttr/detail/type/type_impl.h, src/rttr/rttr.cmake, src/rttr/type.h, src/rttr/wrapper_mapper.h, src/unit_tests/variant/variant_conv_test.cpp
Register for all base classes of the giving type \p T
wrapper converter functions.
The converters are registered in both directions respectively.
From derived to base class and vice versa.
The wrapper_mapper class template, get therefore a new optional
functiont template:
template<typename U>
static std::shared_ptr<U> convert(const type& source, bool& ok)
For the wrapper classes: `std::shared_ptr<T>` and `std::reference_wrapper<T>`
default conversion functions are included.
Example:
```
struct base { virtual ~base() {}; RTTR_ENABLE() };
struct derived : base { virtual ~derived() {}; RTTR_ENABLE(base) };
variant var = std::make_shared<derived>();
var.convert(type::get<std::shared_ptr<base>>());    // yields to `false`
// register the conversion functions …
```
=> added new function in type::register_wrapper_converter_for_base_classes<T>()

src/rttr/detail/type/type_register.cpp, src/unit_tests/type/test_type.cpp
The algorithm was not correct, we had to iterate from the first find key to the end
Like it is done for the metadata for properties, methodes, etc.
fixes #172
=> fixed not correctly retrieved metadata for types

src/unit_tests/instance/instance_test.cpp, src/unit_tests/test_classes.h
Error with clang on OS X are of the form
```
error: destructor called on non-final 'ClassSingle6A' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
```
```
error: destructor called on non-final 'instance_derived' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
```
=> Fixed errors due to missing virtual destructors in some unit tests.

src/rttr/rttr.cmake
client code compile fails without newly added headers installed
=> BUG - missing create_type_visit_func in public interface

src/rttr/detail/base/core_prerequisites.h, src/rttr/rttr_enable.h, src/unit_tests/property/property_class_inheritance.cpp
fixed missing use of 'override' in classes that use RTTR_ENABLE
following test case:
struct s_base
{
virtual ~s_base() = default; // always use virtual dtor in base class
RTTR_ENABLE()
};
struct s_derived : s_base
{
~s_derived() override = default;
// Clang options require "override" on inherited virtual functions
RTTR_ENABLE(s_base)
};
clang warning is: 'get_derived_info' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
The fix is to disable the warning for the usage of RTTR_ENABLE only
=> Bugfix clang virtual override warning

src/rttr/type.cpp, src/unit_tests/method/method_order_test.cpp, src/unit_tests/property/property_order_test.cpp, src/unit_tests/unit_tests.cmake
If you register the same function name in a derived class and in a base class
and call the function via a derived instance
C++ calls the derived method
RTTR calls the base method
RTTR searches from the "base class" to the derived class for the matching name.
The linear search of prop/meth vecs must use reverse iterator
staring from the most derived class registered.
=> BUG - get_method/property uses "base" rather than "most derived"

doc/md_pages/tutorial/register_classes.md
Updated docs to indicate the default policy for class construction is std_shared_ptr.
=> Updated docs for default policy of class construction

src/rttr/detail/type/type_register.cpp, src/rttr/detail/type/type_register_p.h
The base type was removed first and was not removed from the list of base types
on every other type. This lead to a crash.
fixes #199
=> Fix crash for unloading plugins base types

src/rttr/detail/registration/bind_impl.h
This change allows rttr to be build under Visual Studio 2017, with `Conformance Mode` enabled.
=> Modified call to get<T> to be more standard compliant

src/rttr/detail/base/core_prerequisites.h
This fixes the build on aarch64 and riscv64.
https://build.opensuse.org/package/show/home:Andreas_Schwab:Factory/rttr
=> Support all LP64 architectures

src/rttr/variant.h
=> #252 Compiler error because src\rttr\variant.h doesn't include <string>.

src/unit_tests/CMakeLists.txt
LD_LIBRARY_PATH was not set correctly
=> linux: fix unit unit_tests plugin loading
